### ISSUE TITLE
transform this repo into backend service

### ISSUE THREAD

**Issue by Goldensteev** [ontologyExplorer/parmenides#13]
could seperating the backend and frontend into 2 repos make sense?

**Comment by lnmylos** [comment]
> could seperating the backend and frontend into 2 repos make sense?

Depends on our needs, it might be interesting for the reutilisation, sharing of the different parts of the project, it can  simplify the structure of the repo and the collaboration, but it can add additionally complexity for the deployment, versioning and it can add some complexity
But if you feel like experimenting, let's do it. :D

**Comment by Goldensteev** [comment]
I think it could make sense as the backend library could be reused without the frontend for some other purposes? 
and for the development could make things easier. True for deployment and such could make things more challenging but i think we are up for it!
